[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name= "einsingen"
dependencies = [
    "black",
    "django",
    "django-cors-headers",
    "django-ninja",
    "flake8",
    "isort",
    "mido[ports-rtmidi]",
    "pydantic",
    "pytest",
    "pytest-cov",
    "pytest-django"
]
version = "0.0.1"
requires-python = ">= 3.14"

[tool.black]
line-length = 120
skip-string-normalization=false

[tool.pytest]
django_debug_mode = "false"
DJANGO_SETTINGS_MODULE = "einsingen_django.settings"

[tool.setuptools]
packages = ["einsingen"]
package-data = { einsingen = ["midi_notes.json"] }
